#!/usr/bin/env bash
#
# VM Hardening Script
# Security hardening procedures for production VPS instances
#
# Usage:
#   sudo ./scripts/vm-hardening.sh [OPTIONS]
#
# Options:
#   --ssh-port PORT       SSH port (default: 22)
#   --ssh-user USER       SSH user to allow (default: deploy)
#   --skip-ssh            Skip SSH hardening
#   --skip-firewall       Skip UFW firewall setup
#   --skip-fail2ban       Skip fail2ban installation
#   --skip-updates        Skip unattended-upgrades setup
#   --skip-docker         Skip Docker daemon hardening
#   --skip-logrotate      Skip log rotation setup
#   --dry-run             Show what would be done without making changes
#   -h, --help            Show this help message
#
# Environment Variables:
#   SSH_ALLOWED_IPS       Comma-separated list of IPs allowed for SSH
#   CLOUDFLARE_ONLY       Set to 'true' to only allow Cloudflare IPs for HTTP/HTTPS
#
# This script performs the following hardening steps:
#   1. SSH hardening (disable root login, password auth, set port)
#   2. UFW firewall configuration
#   3. fail2ban installation and configuration
#   4. Unattended security upgrades
#   5. Docker daemon security options
#   6. Log rotation configuration

set -euo pipefail

# Default values
SSH_PORT="22"
SSH_USER="deploy"
DRY_RUN="false"
SKIP_SSH="false"
SKIP_FIREWALL="false"
SKIP_FAIL2BAN="false"
SKIP_UPDATES="false"
SKIP_DOCKER="false"
SKIP_LOGROTATE="false"

# Cloudflare IPv4 ranges
CLOUDFLARE_IPV4=(
    "173.245.48.0/20"
    "103.21.244.0/22"
    "103.22.200.0/22"
    "103.31.4.0/22"
    "141.101.64.0/18"
    "108.162.192.0/18"
    "190.93.240.0/20"
    "188.114.96.0/20"
    "197.234.240.0/22"
    "198.41.128.0/17"
    "162.158.0.0/15"
    "104.16.0.0/13"
    "104.24.0.0/14"
    "172.64.0.0/13"
    "131.0.72.0/22"
)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

show_help() {
    head -35 "$0" | grep "^#" | sed 's/^# \?//'
    exit 0
}

run_cmd() {
    if [[ "$DRY_RUN" == "true" ]]; then
        echo "[DRY-RUN] $*"
    else
        "$@"
    fi
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

#------------------------------------------------------------------------------
# SSH Hardening
#------------------------------------------------------------------------------
harden_ssh() {
    log_step "Configuring SSH hardening..."

    local sshd_config="/etc/ssh/sshd_config"

    if [[ ! -f "$sshd_config" ]]; then
        log_error "SSH config file not found: $sshd_config"
        return 1
    fi

    # Backup original config
    if [[ ! -f "${sshd_config}.original" ]]; then
        run_cmd cp "$sshd_config" "${sshd_config}.original"
        log_info "Backed up original SSH config"
    fi

    # Create hardened SSH config
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would write hardened SSH config"
    else
        cat > "$sshd_config" << EOF
# SSH Server Configuration - Hardened
# Generated by vm-hardening.sh

# Network
Port $SSH_PORT
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Authentication
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Security
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
MaxAuthTries 3
MaxSessions 3
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60

# Restrict users
AllowUsers $SSH_USER

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# SFTP
Subsystem sftp /usr/lib/openssh/sftp-server

# Host keys
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# Key exchange and ciphers (secure defaults)
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
EOF
        log_info "Wrote hardened SSH config"
    fi

    # Test SSH config before restarting
    if [[ "$DRY_RUN" != "true" ]]; then
        if sshd -t; then
            log_info "SSH config test passed"
            run_cmd systemctl restart sshd
            log_info "SSH service restarted"
        else
            log_error "SSH config test failed! Restoring original..."
            cp "${sshd_config}.original" "$sshd_config"
            exit 1
        fi
    fi

    log_info "SSH hardening complete (port: $SSH_PORT, user: $SSH_USER)"
}

#------------------------------------------------------------------------------
# UFW Firewall Configuration
#------------------------------------------------------------------------------
setup_firewall() {
    log_step "Configuring UFW firewall..."

    # Install UFW if not present
    if ! command -v ufw &> /dev/null; then
        run_cmd apt-get update
        run_cmd apt-get install -y ufw
    fi

    # Reset UFW to defaults
    run_cmd ufw --force reset

    # Set default policies
    run_cmd ufw default deny incoming
    run_cmd ufw default allow outgoing

    # Allow SSH
    if [[ -n "${SSH_ALLOWED_IPS:-}" ]]; then
        # Restrict SSH to specific IPs
        IFS=',' read -ra IPS <<< "$SSH_ALLOWED_IPS"
        for ip in "${IPS[@]}"; do
            ip=$(echo "$ip" | xargs)  # Trim whitespace
            run_cmd ufw allow from "$ip" to any port "$SSH_PORT" proto tcp comment "SSH from $ip"
            log_info "Allowed SSH from: $ip"
        done
    else
        # Allow SSH from anywhere (not recommended for production)
        run_cmd ufw allow "$SSH_PORT"/tcp comment "SSH"
        log_warn "SSH allowed from anywhere - consider restricting with SSH_ALLOWED_IPS"
    fi

    # HTTP/HTTPS rules
    if [[ "${CLOUDFLARE_ONLY:-false}" == "true" ]]; then
        log_info "Configuring HTTP/HTTPS for Cloudflare IPs only..."
        for ip in "${CLOUDFLARE_IPV4[@]}"; do
            run_cmd ufw allow from "$ip" to any port 80 proto tcp comment "HTTP from Cloudflare"
            run_cmd ufw allow from "$ip" to any port 443 proto tcp comment "HTTPS from Cloudflare"
        done
    else
        run_cmd ufw allow 80/tcp comment "HTTP"
        run_cmd ufw allow 443/tcp comment "HTTPS"
    fi

    # Enable UFW
    run_cmd ufw --force enable

    log_info "UFW firewall configured and enabled"

    if [[ "$DRY_RUN" != "true" ]]; then
        ufw status verbose
    fi
}

#------------------------------------------------------------------------------
# fail2ban Configuration
#------------------------------------------------------------------------------
setup_fail2ban() {
    log_step "Installing and configuring fail2ban..."

    # Install fail2ban
    if ! command -v fail2ban-client &> /dev/null; then
        run_cmd apt-get update
        run_cmd apt-get install -y fail2ban
    fi

    # Create jail.local configuration
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would write fail2ban jail.local config"
    else
        cat > /etc/fail2ban/jail.local << EOF
# fail2ban configuration - Generated by vm-hardening.sh

[DEFAULT]
# Ban duration (1 hour)
bantime = 3600
# Time window for counting failures
findtime = 600
# Number of failures before ban
maxretry = 3
# Action to take
banaction = ufw
backend = systemd

# Email notifications (optional - configure sendmail first)
# destemail = admin@example.com
# sender = fail2ban@example.com
# action = %(action_mwl)s

[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600

# Protect against aggressive SSH scanning
[sshd-aggressive]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 1
bantime = 86400
findtime = 86400
EOF
        log_info "Wrote fail2ban configuration"
    fi

    # Enable and start fail2ban
    run_cmd systemctl enable fail2ban
    run_cmd systemctl restart fail2ban

    log_info "fail2ban installed and configured"

    if [[ "$DRY_RUN" != "true" ]]; then
        fail2ban-client status
    fi
}

#------------------------------------------------------------------------------
# Unattended Upgrades
#------------------------------------------------------------------------------
setup_unattended_upgrades() {
    log_step "Configuring unattended security upgrades..."

    # Install unattended-upgrades
    run_cmd apt-get update
    run_cmd apt-get install -y unattended-upgrades apt-listchanges

    # Configure automatic security updates
    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure unattended-upgrades"
    else
        cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
// Unattended upgrades configuration - Generated by vm-hardening.sh

Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

// Remove unused kernel packages after upgrade
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatically reboot if required (at 3:00 AM)
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";

// Send email on upgrade (requires mail setup)
// Unattended-Upgrade::Mail "admin@example.com";
// Unattended-Upgrade::MailReport "on-change";

// Log syslog
Unattended-Upgrade::SyslogEnable "true";
Unattended-Upgrade::SyslogFacility "daemon";
EOF

        cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF
        log_info "Wrote unattended-upgrades configuration"
    fi

    # Enable the service
    run_cmd systemctl enable unattended-upgrades
    run_cmd systemctl restart unattended-upgrades

    log_info "Unattended security upgrades configured"
}

#------------------------------------------------------------------------------
# Docker Daemon Hardening
#------------------------------------------------------------------------------
harden_docker() {
    log_step "Configuring Docker daemon security..."

    if ! command -v docker &> /dev/null; then
        log_warn "Docker not installed, skipping Docker hardening"
        return 0
    fi

    local docker_config="/etc/docker/daemon.json"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would write Docker daemon config"
    else
        # Create docker config directory if it doesn't exist
        mkdir -p /etc/docker

        cat > "$docker_config" << 'EOF'
{
    "userns-remap": "default",
    "live-restore": true,
    "userland-proxy": false,
    "no-new-privileges": true,
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "10m",
        "max-file": "3"
    },
    "storage-driver": "overlay2",
    "default-ulimits": {
        "nofile": {
            "Name": "nofile",
            "Hard": 65536,
            "Soft": 65536
        }
    }
}
EOF
        log_info "Wrote Docker daemon configuration"

        # Restart Docker to apply changes
        run_cmd systemctl restart docker
        log_info "Docker daemon restarted with security settings"
    fi

    log_info "Docker daemon hardening complete"
}

#------------------------------------------------------------------------------
# Log Rotation Configuration
#------------------------------------------------------------------------------
setup_logrotate() {
    log_step "Configuring log rotation..."

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure log rotation"
    else
        # Custom logrotate config for application logs
        cat > /etc/logrotate.d/app-logs << 'EOF'
/var/log/app/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 root adm
    sharedscripts
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}
EOF

        # Ensure syslog logrotate is properly configured
        cat > /etc/logrotate.d/syslog << 'EOF'
/var/log/syslog
/var/log/mail.info
/var/log/mail.warn
/var/log/mail.err
/var/log/mail.log
/var/log/daemon.log
/var/log/kern.log
/var/log/auth.log
/var/log/user.log
/var/log/lpr.log
/var/log/cron.log
/var/log/debug
/var/log/messages
{
    rotate 7
    daily
    missingok
    notifempty
    compress
    delaycompress
    sharedscripts
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}
EOF
        log_info "Log rotation configured"
    fi

    # Create app log directory if it doesn't exist
    run_cmd mkdir -p /var/log/app

    log_info "Log rotation setup complete"
}

#------------------------------------------------------------------------------
# Parse Arguments
#------------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case $1 in
        --ssh-port)
            SSH_PORT="$2"
            shift 2
            ;;
        --ssh-user)
            SSH_USER="$2"
            shift 2
            ;;
        --skip-ssh)
            SKIP_SSH="true"
            shift
            ;;
        --skip-firewall)
            SKIP_FIREWALL="true"
            shift
            ;;
        --skip-fail2ban)
            SKIP_FAIL2BAN="true"
            shift
            ;;
        --skip-updates)
            SKIP_UPDATES="true"
            shift
            ;;
        --skip-docker)
            SKIP_DOCKER="true"
            shift
            ;;
        --skip-logrotate)
            SKIP_LOGROTATE="true"
            shift
            ;;
        --dry-run)
            DRY_RUN="true"
            shift
            ;;
        -h|--help)
            show_help
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            ;;
    esac
done

#------------------------------------------------------------------------------
# Main Execution
#------------------------------------------------------------------------------
main() {
    log_info "Starting VM hardening..."
    log_info "SSH Port: $SSH_PORT"
    log_info "SSH User: $SSH_USER"
    [[ "$DRY_RUN" == "true" ]] && log_warn "DRY-RUN mode enabled"

    check_root

    [[ "$SKIP_SSH" != "true" ]] && harden_ssh
    [[ "$SKIP_FIREWALL" != "true" ]] && setup_firewall
    [[ "$SKIP_FAIL2BAN" != "true" ]] && setup_fail2ban
    [[ "$SKIP_UPDATES" != "true" ]] && setup_unattended_upgrades
    [[ "$SKIP_DOCKER" != "true" ]] && harden_docker
    [[ "$SKIP_LOGROTATE" != "true" ]] && setup_logrotate

    log_info "VM hardening completed successfully!"
    log_info ""
    log_info "Next steps:"
    log_info "  1. Verify SSH access with your key before logging out"
    log_info "  2. Run ./scripts/verify-hardening.sh to verify all settings"
    log_info "  3. Test fail2ban with: fail2ban-client status sshd"
    log_info "  4. Check firewall with: ufw status verbose"
}

main
